### Example config file

# Values from the DEFAULT section are applied to all devices, other sections with the
# MAC address can override config elements for the specific device.
# Only devices that have a section are considered by the auto detection mechanism, but
# it can be empty to run with pure defaults.

# Key names are identical to the long parameters without dashes:
# specify "mtu = 20" to get "--mtu 20", this works also with flags like "--verbose".
# The only special key is "executable", which specifies the program that is started.

[DEFAULT]
executable = ble-serial
timeout = 10
mtu = 247
; port = /tmp/ttyBLE

; [88:56:A6:64:91:9A]
; dev = 88:56:A6:64:91:9A
; address-type = public
; name = ESP32_BRIDGE
; expose-tcp-port = 4002
; port = /tmp/UT61E
; verbose

; [58:8C:81:AE:94:BA]
; dev = 58:8C:81:AE:94:BA
; address-type = public
; name = ESP32_BRIDGE
; expose-tcp-port = 4002

[58:8C:81:AC:61:BE]
dev = 58:8C:81:AC:61:BE
address-type = public
name = ESP32_BRIDGE
expose-tcp-port = 4002

; [48:F6:EE:32:01:22]
; dev = 48:F6:EE:32:01:22
; address-type = public
; name = ESP32_BRIDGE
; expose-tcp-port = 4002

; [CE:AE:42:0E:3E:D6]
; dev = CE:AE:42:0E:3E:D6
; address-type = public
; name = NRF52_BRIDGE
; expose-tcp-port = 4002

; [D5:50:D1:6E:D8:8B]
; dev = D5:50:D1:6E:D8:8B
; address-type = public
; name = MB06BA_BRIDGE
; expose-tcp-port = 4002
