### Example config file

# Values from the DEFAULT section are applied to all devices, other sections with the
# MAC address can override config elements for the specific device.
# Only devices that have a section are considered by the auto detection mechanism, but
# it can be empty to run with pure defaults.

# Key names are identical to the long parameters without dashes:
# specify "mtu = 20" to get "--mtu 20", this works also with flags like "--verbose".
# The only special key is "executable", which specifies the program that is started.

[DEFAULT]
; executable = ble-serial
executable = D:\ProgramData\anaconda3\envs\zzzenv\Scripts\ble-serial.exe
timeout = 10
mtu = 247
; port = /tmp/ttyBLE


[C1:4F:8F:9D:CD:F8]
dev = C1:4F:8F:9D:CD:F8
address-type = public
name = Nordic_UART_Service
expose-tcp-port = 4002
; port = /tmp/UT61E
; verbose

[C0:34:F5:EB:FE:5A]
dev = C0:34:F5:EB:FE:5A
address-type = public
name = Nordic_UART_Service
expose-tcp-port = 4002