; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./

[env:nucleo_h723zg]
platform = ststm32
board = nucleo_h723zg
; framework = stm32cube
platform_packages = 
    toolchain-gccarmnoneeabi @ ~1.90201.191206
; 	framework-stm32cubeh7 @ 1.12.1
lib_deps =
lib_ignore = 
    STM32_USB_Device_Library-CDC
    STM32_USB_Device_Library-Core
build_src_filter = 
    +<Drivers/>
    +<Core/>
    +<Middlewares/>
    +<USB_DEVICE/>
build_unflags = 
    -mfloat-abi=soft
    -mfloat-abi=softfp
build_flags = 
	-D STM32H723xx
	-D USE_HAL_DRIVER
    -D USE_PWR_LDO_SUPPLY
	-D DEBUG
	-I Core/Inc
    -I Core/UserInc
    -I Core/UserPortLib/agile_modbus/inc
    -I Core/UserPortLib/agile_modbus/util
    -I Drivers/STM32H7xx_HAL_Driver/Inc
    -I Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    -I Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -I Drivers/CMSIS/Include
    -I Drivers/CMSIS/DSP/Include
    -I Middlewares/ST/STM32_USB_Device_Library/Core/Inc
    -I Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
    -I USB_DEVICE/App
    -I USB_DEVICE/Target
    -L Drivers/CMSIS/DSP/Lib/GCC
    -l libarm_cortexM7lfdp_math.a  ; ABI类型: libarm_cortexM7lfdp_math-硬浮点; libarm_cortexM7lfsp_math-单精度硬浮点; libarm_cortexM7l_math-软浮点
    ; 编译与链接统一浮点参数
    -mcpu=cortex-m7
    -mfloat-abi=hard
    -mfpu=fpv5-d16
    -mthumb
    --specs=nano.specs
build_type = debug
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.custom_system_setup = yes
board_build.stm32cube.system_file = ./Core/Src/system_stm32h7xx.c
board_build.stm32cube.startup_file = ./Core/Startup/startup_stm32h723vgtx.s
board_build.stm32cube.disable_embedded_libs = no
board_build.ldscript = PIO_STM32H723VGTx_FLASH.ld
upload_protocol = stlink
debug_tool = stlink
extra_scripts = update_link_flags.py, post:export_hex.py
monitor_port = COM3
monitor_speed = 115200
monitor_encoding = UTF-8

