"""
Design Butterworth bandpass / lowpass / highpass filters and export coefficients
for ARM CMSIS-DSP arm_biquad_cascade_df2T_f32().

Usage:
    python design_biquad_filter.py          # run with defaults, print C++ code
    python design_biquad_filter.py --plot   # also plot frequency response
    python design_biquad_filter.py -h       # full help

Dependencies: numpy, scipy, matplotlib (optional, for --plot)
"""

import argparse
import sys

import numpy as np
from scipy import signal


def design_bandpass(fs, f_low, f_high, order):
    """Design a Butterworth bandpass, return SOS matrix."""
    sos = signal.butter(order, [f_low, f_high], btype='band',
                        analog=False, output='sos', fs=fs)
    return sos


def design_lowpass(fs, cutoff, order):
    """Design a Butterworth lowpass, return SOS matrix."""
    sos = signal.butter(order, cutoff, btype='lowpass',
                        analog=False, output='sos', fs=fs)
    return sos


def design_highpass(fs, cutoff, order):
    """Design a Butterworth highpass, return SOS matrix (with DC blocker)."""
    sos = signal.butter(order, cutoff, btype='highpass',
                        analog=False, output='sos', fs=fs)
    return sos


def design_bandstop(fs, f_low, f_high, order):
    """Design a Butterworth bandstop (notch), return SOS matrix (for 50 Hz notch)."""
    sos = signal.butter(order, [f_low, f_high], btype='bandstop',
                        analog=False, output='sos', fs=fs)
    return sos


def sos_to_cmsis_direct(sos):
    """
    Convert scipy SOS matrix to CMSIS-DSP DF2T biquad cascade coefficients.

    scipy SOS row:     [b0,  b1,  b2,  a0,  a1,  a2]   (a0 always 1)
                      H(z) = (b0 + b1·z⁻¹ + b2·z⁻²) / (a0 + a1·z⁻¹ + a2·z⁻²)

    CMSIS-DSP DF2T:    {b0,  b1,  b2,  a1,  a2}
                      H(z) = (b0 + b1·z⁻¹ + b2·z⁻²) / (1 - a1·z⁻¹ - a2·z⁻²)

    注意: 两个格式的 a 系数符号相反! scipy 分母是 (1 + a1·z⁻¹ + a2·z⁻²),
    CMSIS-DSP DF2T 分母是 (1 - a1·z⁻¹ - a2·z⁻²). 因此需要取反 a1, a2.

    Returns (num_stages, flat_coeff_list).
    """
    coeffs = []
    for row in sos:
        b0, b1, b2, a0, a1, a2 = row
        if not np.isclose(a0, 1.0, atol=1e-12):
            print(f"  [WARNING] a0 = {a0:.12f}, expected 1.0. Normalising...",
                  file=sys.stderr)
            b0, b1, b2 = b0 / a0, b1 / a0, b2 / a0
            a1, a2 = a1 / a0, a2 / a0
        # CMSIS-DSP DF2T 需要取反 a 系数 (见函数文档)
        coeffs.extend([b0, b1, b2, -a1, -a2])
    return sos.shape[0], coeffs


def sos_to_cmsis_blockfloat(sos, shift_bits=8):
    """
    Convert scipy SOS to CMSIS-DSP DF2T biquad coefficients with fixed-point
    block‑floating‑point scaling.

    This produces the `coeffs` and `postShift` arrays used by the q15/q31
    variants:

        arm_biquad_cascade_df2T_f32  → use sos_to_cmsis_direct()
        arm_biquad_cascade_df2T_init_q31  → use this function

    Returns (num_stages, coeffs, postShift).
    """
    coeffs = []
    postShift = []
    for row in sos:
        b0, b1, b2, a0, a1, a2 = row
        if not np.isclose(a0, 1.0, atol=1e-12):
            b0, b1, b2 = b0 / a0, b1 / a0, b2 / a0
            a1, a2 = a1 / a0, a2 / a0

        stage_coeffs = [b0, b1, b2, -a1, -a2]  # CMSIS-DSP DF2T 需要取反 a
        max_val = max(abs(c) for c in stage_coeffs)
        if max_val > 1.0:
            shift = 0
            while max_val > 1.0:
                max_val /= 2.0
                shift += 1
            stage_coeffs = [c / (1 << shift) for c in stage_coeffs]
        else:
            shift = 0
        coeffs.extend(stage_coeffs)
        postShift.append(shift)
    return sos.shape[0], coeffs, postShift


def plot_response(sos, fs, title):
    """Plot frequency and phase response of the SOS cascade."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("[SKIP] matplotlib not installed, cannot plot.", file=sys.stderr)
        return

    whole_sys = signal.sosfreqz(sos, worN=8192, fs=fs)
    w, h = whole_sys
    mag = 20 * np.log10(np.abs(h) + 1e-16)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 7), sharex=True)
    fig.suptitle(title)

    # Magnitude
    ax1.plot(w, mag)
    ax1.set_ylabel('Magnitude [dB]')
    ax1.grid(True, alpha=0.3)
    ax1.set_xscale('log')
    ax1.set_ylim([-80, 5])
    ax1.axhline(-3, color='r', linestyle='--', alpha=0.5, label='-3 dB')
    ax1.legend(loc='upper right')

    # Phase
    phase = np.unwrap(np.angle(h))
    ax2.plot(w, phase)
    ax2.set_xlabel('Frequency [Hz]')
    ax2.set_ylabel('Phase [rad]')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()


def print_c_header(coeffs, num_stages, var_name, desc):
    """Pretty-print coefficients as a C/C++ array initialiser."""
    print(f"// {desc}")
    print(f"// Auto-generated by design_biquad_filter.py")
    print(f"constexpr int {var_name}_num_stages = {num_stages};")
    print(f"const float32_t {var_name}_coeffs[{5 * num_stages}] = {{")
    for i in range(num_stages):
        base = i * 5
        print(f"    {coeffs[base+0]: .8f}f, "
              f"{coeffs[base+1]: .8f}f, "
              f"{coeffs[base+2]: .8f}f, "
              f"{coeffs[base+3]: .8f}f, "
              f"{coeffs[base+4]: .8f}f,   // stage {i}")
    print("};")
    print()


def main():
    parser = argparse.ArgumentParser(
        description='Design Butterworth filters and export CMSIS-DSP coefficients.')
    parser.add_argument('--fs', type=float, default=1000,
                        help='Sampling frequency [Hz] (default: 1000)')
    parser.add_argument('--type', choices=['bandpass', 'lowpass', 'highpass', 'bandstop'],
                        default='bandpass', help='Filter type (default: bandpass)')
    parser.add_argument('--order', type=int, default=4,
                        help='Filter order (default: 4 → bandpass uses 2 SOS sections)')
    parser.add_argument('--low', type=float, default=20,
                        help='Low cutoff for bandpass/bandstop [Hz] (default: 20)')
    parser.add_argument('--high', type=float, default=450,
                        help='High cutoff for bandpass/bandstop [Hz] (default: 450)')
    parser.add_argument('--cutoff', type=float, default=100,
                        help='Cutoff for lowpass/highpass [Hz] (default: 100)')
    parser.add_argument('--plot', action='store_true',
                        help='Show frequency response plot')
    parser.add_argument('--var', type=str, default='filter',
                        help='C variable base name (default: filter)')
    parser.add_argument('--dump-raw', action='store_true',
                        help='Also print raw SOS matrix from scipy')
    parser.add_argument('--q31', action='store_true',
                        help='Also output block-floating-point coeffs for Q31 variant')

    args = parser.parse_args()

    # Design
    if args.type == 'bandpass':
        sos = design_bandpass(args.fs, args.low, args.high, args.order)
        desc = (f"Butterworth bandpass, fs={args.fs} Hz, "
                f"f_low={args.low} Hz, f_high={args.high} Hz, order={args.order}")
    elif args.type == 'lowpass':
        sos = design_lowpass(args.fs, args.cutoff, args.order)
        desc = (f"Butterworth lowpass, fs={args.fs} Hz, "
                f"cutoff={args.cutoff} Hz, order={args.order}")
    elif args.type == 'highpass':
        sos = design_highpass(args.fs, args.cutoff, args.order)
        desc = (f"Butterworth highpass, fs={args.fs} Hz, "
                f"cutoff={args.cutoff} Hz, order={args.order}")
    elif args.type == 'bandstop':
        sos = design_bandstop(args.fs, args.low, args.high, args.order)
        desc = (f"Butterworth bandstop, fs={args.fs} Hz, "
                f"f_low={args.low} Hz, f_high={args.high} Hz, order={args.order}")

    if args.dump_raw:
        print("// ========== Raw scipy SOS matrix ==========")
        print(f"// {sos.shape[0]} sections, {5 * sos.shape[0]} CMSIS coeffs")
        for i, row in enumerate(sos):
            print(f"// stage {i}:  b=[{row[0]:.8f}, {row[1]:.8f}, {row[2]:.8f}]  "
                  f"a=[{row[3]:.8f}, {row[4]:.8f}, {row[5]:.8f}]")
        print()

    # Convert
    num_stages, coeffs = sos_to_cmsis_direct(sos)

    # Print C/C++ header
    print_c_header(coeffs, num_stages, args.var, desc)

    # Q31 if requested
    if args.q31:
        _, q31_coeffs, shifts = sos_to_cmsis_blockfloat(sos)
        print(f"// --- Q31 block-floating-point variant ---")
        print(f"const int8_t {args.var}_postShift[{num_stages}] = {{")
        for i, s in enumerate(shifts):
            print(f"    {s},   // stage {i}")
        print("};")
        print_c_header(q31_coeffs, num_stages, args.var + "_q31",
                       desc + " (Q31 block-float)")

    # Usage hint
    print("// ========== Usage in sEmg class ==========")
    print(f"// sEmg emg;")
    print(f"// emg.SetFilterCoeffs({args.var}_coeffs, {args.var}_num_stages);")
    print()

    # Plot
    if args.plot:
        plot_response(sos, args.fs, desc)


if __name__ == '__main__':
    main()
